# Generated by Django 4.2 on 2025-02-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce1',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Validee', 'Validee'), ('Rejetee', 'Rejetee')], default='En attente', max_length=16),
            preserve_default=False,
        ),
    ]
