# Generated by Django 3.2.25 on 2025-07-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceuil', '0002_annonce1_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce1',
            name='status',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Validee', 'Validee'), ('Rejetee', 'Rejetee')], default='En attente', max_length=16),
        ),
    ]
