# Generated by Django 4.2 on 2025-02-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_utilisateurs_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='role',
            field=models.CharField(default='vandeur', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
