# Generated by Django 3.2.25 on 2025-07-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_alter_utilisateurs_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='role',
            field=models.CharField(choices=[('vandeur', 'vandeur'), ('admin', 'admin')], default='vandeur', max_length=10, null=True),
        ),
    ]
